let attori = [
  {
    name: "Tom Cruise",
    age: 56,
    "Born At": "Syracuse, NY",
    Birthdate: "July 3, 1962",
    photo: "https://jsonformatter.org/img/tom-cruise.jpg",
    wife: null,
    weight: 67.5,
    hasChildren: true,
    hasGreyHair: false,
    children: ["Suri", "Isabella Jane", "Connor"],
  },
  {
    name: "Robert Downey Jr.",
    age: 53,
    "Born At": "New York City, NY",
    Birthdate: "April 4, 1965",
    photo: "https://jsonformatter.org/img/Robert-Downey-Jr.jpg",
    wife: "Susan Downey",
    weight: 77.1,
    hasChildren: true,
    hasGreyHair: false,
    children: ["Indio Falconer", "Avri Roel", "Exton Elias"],
  },
  {
    name: "Brad Pitt",
    age: 58,
    "Born At": "Shawnee, OK",
    Birthdate: "December 18, 1963",
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Brad_Pitt_2019_by_Glenn_Francis.jpg/800px-Brad_Pitt_2019_by_Glenn_Francis.jpg",
    wife: null,
    weight: 75.2,
    hasChildren: true,
    hasGreyHair: false,
    children: [
      "Shiloh Nouvel",
      "Knox Léon",
      "Vivienne Marcheline",
      "Maddox Chivan",
      "Pax Thien",
      "Zahara Marley",
    ],
  },
  {
    name: "Angelina Jolie",
    age: 46,
    "Born At": "Los Angeles, CA",
    Birthdate: "June 4, 1975",
    photo:
      "https://m.media-amazon.com/images/M/MV5BODg3MzYwMjE4N15BMl5BanBnXkFtZTcwMjU5NzAzNw@@._V1_FMjpg_UX1000_.jpg",
    husband: null,
    weight: 58.9,
    hasChildren: true,
    hasGreyHair: false,
    children: ["Maddox", "Pax", "Zahara", "Shiloh", "Knox", "Vivienne"],
  },

  {
    name: "Leonardo DiCaprio",
    age: 47,
    "Born At": "Los Angeles, CA",
    Birthdate: "November 11, 1974",
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/LeonardoDiCaprioNov08.jpg/220px-LeonardoDiCaprioNov08.jpg",
    wife: null,
    weight: 80.5,
    hasChildren: false,
    hasGreyHair: false,
  },

  {
    name: "Scarlett Johansson",
    age: 37,
    "Born At": "New York City, NY",
    Birthdate: "November 22, 1984",
    photo: "https://jsonformatter.org/img/scarlett-johansson.jpg",
    husband: "Colin Jost",
    weight: 57.3,
    hasChildren: true,
    hasGreyHair: false,
    children: ["Rose Dorothy"],
  },

  {
    name: "Chris Hemsworth",
    age: 38,
    "Born At": "Melbourne, Australia",
    Birthdate: "August 11, 1983",
    photo: "https://jsonformatter.org/img/chris-hemsworth.jpg",
    wife: "Elsa Pataky",
    weight: 91.7,
    hasChildren: true,
    hasGreyHair: false,
    children: ["India Rose", "Tristan", "Sasha"],
  },

  {
    name: "Gal Gasdotto",
    age: 37,
    "Born At": "Petah Tikva, Israel",
    Birthdate: "April 30, 1985",
    photo: "https://jsonformatter.org/img/gal-gadot.jpg",
    husband: "Yaron Varsano",
    weight: 59.4,
    hasChildren: true,
    hasGreyHair: false,
    children: ["Alma", "Maya"],
  },

  {
    name: "Dwayne Johnson",
    age: 50,
    "Born At": "Hayward, CA",
    Birthdate: "May 2, 1972",
    photo:
      "https://ih0.redbubble.net/image.2990817857.2109/raf,360x360,075,t,fafafa:ca443f4786.jpg",
    wife: "Lauren Hashian",
    weight: 118.2,
    hasChildren: true,
    hasGreyHair: false,
    children: ["Simone", "Jasmine", "Tiana"],
  },

  {
    name: "Emma Stone",
    age: 33,
    "Born At": "Scottsdale, AZ",
    Birthdate: "November 6, 1988",
    photo: "https://jsonformatter.org/img/emma-stone.jpg",
    husband: "Dave McCary",
    weight: 53.8,
    hasChildren: false,
    hasGreyHair: false,
  },

  {
    name: "Ryan Reynolds",
    age: 45,
    "Born At": "Vancouver, Canada",
    Birthdate: "October 23, 1976",
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg/1200px-Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg+",
    wife: "Blake Lively",
    weight: 84.6,
    hasChildren: true,
    hasGreyHair: false,
    children: ["James", "Inez", "Betty"],
  },

  {
    name: "Margot Robbie",
    age: 32,
    "Born At": "Dalby, Australia",
    Birthdate: "July 2, 1990",
    photo: "https://jsonformatter.org/img/margot-robbie.jpg",
    husband: "Tom Ackerley",
    weight: 57.1,
    hasChildren: false,
    hasGreyHair: false,
  },
];
